language: node_js
node_js:
  - 0.10
  - 0.11
matrix:
    allow_failures:
        - node_js: 0.11
    fast_finish: true
script:
    - karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
